### ISSUE TITLE
Freeze at bootup if second workspace clicked through pager

### ISSUE THREAD

**Issue by petersonespacoporto** [d86leader/dynamic_workspaces#3]
Hi, thanks for the script!

It's working wonders except for one thing: if the first thing I do when I log into the desktop is to click on the second workspace on the panel's pager, the whole GUI freezes. I can only move the mouse around, but clicking has no effect and no apps open (for instance, through keyboard shortcuts). I can then move to a virtual terminal at ctrl+alt+F2.

I'm using NVidia's driver, and can send more hardware details if that's needed.

**Comment by d86leader** [comment]
Hello!
This is probably another KDE bug. What version of plasma and Qt is installed on your system?

1. When your desktop starts up, are there any windows that start on their own? If they do, on what desktop do they appear? Do they have any Special Window Settings?

2. What happens if you try to switch desktop with keyboard hotkeys?

**Comment by petersonespacoporto** [comment]
Hi, thanks for taking the time to look at this!

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-37-generic
OS Type: 64-bit

1. No, nothing autostarts as a window on its own.
2. I need a stable system for several hours today but will try this out as soon as I can and report back.

**Comment by petersonespacoporto** [comment]
I can confirm this also happens when shorcut-changing workspaces.

**Comment by d86leader** [comment]
Thanks for your report, I managed to reproduce the issue (or a very similar issue?) on radeon and intel graphics, and on different plasma versions. My steps are a bit different:
1. Doesn't matter if it's startup, what matters is there are no windows or all windows are set to be shown on all desktops
2. Start on the first desktop and move to the second - it works without problems for me fine
3. Then I return to the first desktop and kwin freezes. It consumes 100% CPU and doesn't respond to SIGTERM or `kwin_x11 --replace`

So a workaround is to always have a window open on some desktop. I think I never noticed it because I always have ktorrent in my second activity, or because the first thing I do is open firefox.

I'll comment later if I manage to fix this.

**Comment by petersonespacoporto** [comment]
Ahh it makes sense that it doesn't only affect startup. I hadn't thought of that. And I also usually open something first thing I log in, I guess I stumbled upon this bug.

Thanks for your efforts in reproducing it and striving to fix it! I hope there's a simple solution :)

**Comment by d86leader** [comment]
The problem is fixed for me in the latest commit (which I'll soon upload to freedesktop), please check for yourself and reopen if it persists
