### ISSUE TITLE
Plasma Desktop Creashes on switching 

### ISSUE THREAD

**Issue by Da-Viper** [d86leader/dynamic_workspaces#5]
Operating System: Manjaro Linux
KDE Plasma Version: 5.19.4
KDE Frameworks Version: 5.72.0
Qt Version: 5.15.0
Kernel Version: 5.7.14-1-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i5-8265U CPU @ 1.60GHz
Memory: 7.5 GiB of RAM
Graphics Processor: GeForce GTX 1650 with Max-Q Design/PCIe/SSE2

Scenario 
there is two open workspaces with no apps on either of them , and you want to switch through them 
(workspaces is switched using a  shortcut ) . and you switch through them like multiple times with the shortcut 

expected result : 
it switches workspaces 

observed result : 
plasma desktop crashes and you have to restart to get a working desktop

**Comment by d86leader** [comment]
Thanks for the datailed report. I tried it just now on my Plasma 5.18, and couldn't manage it to crash no matter how fast and violent I switched the desktops, with the shortcuts and with the mouse wheel. I'll try it later with a 5.19 on another computer.

Are you sure this is not caused by another script or by broken plasma version in your distro? You sure this doesn't happen without my script activated?

**Comment by Da-Viper** [comment]
Hello It no longer crashes the desktop .

It started when I updated the script while it was running and also updated plasma 5.19(this version broke a lot of things in kde )  so I turned of the script, uninstalled it completely  and reinstalled it , it's now working perfectly it was probably plasma update

**Comment by d86leader** [comment]
Ok, crashing after updates is an expected behaviour for plasma (=
